# Generated by Django 5.2.3 on 2025-06-25 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c868', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='min_invetory',
            new_name='min_inventory',
        ),
    ]
