# Generated by Django 5.2.3 on 2025-06-25 06:20

import c868.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c868', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sku', models.CharField(max_length=64)),
                ('source', models.CharField(choices=[('IH', 'In House'), ('OS', 'Outsourced')], default='IH', max_length=15)),
                ('source_id', models.CharField(max_length=64)),
                ('inventory_level', models.IntegerField(validators=[c868.validators.validateInventory])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_inventory', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Must be greater than 0.'), c868.validators.validateMaxMin])),
                ('min_invetory', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Must be greater than or equal to 0.')])),
                ('sub_parts', models.ManyToManyField(to='c868.part')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
            },
        ),
    ]
