# Generated by Django 5.2.3 on 2025-06-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c868', '0002_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='inventory_level',
            new_name='inventory',
        ),
    ]
