# Generated by Django 5.2.3 on 2025-06-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c868', '0002_rename_min_invetory_part_min_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='sub_parts',
            field=models.ManyToManyField(blank=True, related_name='parent_part', to='c868.part'),
        ),
    ]
