# Generated by Django 5.2.3 on 2025-06-25 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c868', '0003_rename_inventory_level_part_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='inventory',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='part',
            name='max_inventory',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Must be greater than 0.')]),
        ),
        migrations.AlterField(
            model_name='part',
            name='sub_parts',
            field=models.ManyToManyField(blank=True, to='c868.part'),
        ),
    ]
