# Generated by Django 5.2.3 on 2025-06-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c868', '0003_alter_part_sub_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
